name: Build and Deploy Python Docker App

on:
  push:
    branches:
      - staging
      - master    
  pull_request:
    branches:
      - staging     
      - master    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2   

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2   

      - name: Log in to DockerHub
        uses: docker/login-action@v2    
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/python-app:${{ github.sha }} .
          

      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/python-app:${{ github.sha }}
          

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'  
    needs: build  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2   

      - name: Deploy to production
        run: |
          echo "Deploying Docker container to production..."  
